### ISSUE TITLE
can you add image cropping?

### ISSUE THREAD

**Issue by bibekmakaju** [flutter-package/flutter_scan#11]
Image cropping for qr code image

**Comment by chavesgu** [comment]
images_picker includes crop
----------

该邮件从移动设备发送



--------------原始邮件--------------
发件人："bibekmakaju ***@***.***&gt;;
发送时间：2021年4月27日(星期二) 下午5:52
收件人："flutter-package/flutter_scan" ***@***.***&gt;;
抄送："Subscribed ***@***.***&gt;;
主题：[flutter-package/flutter_scan] can you add image cropping? (#11)
-----------------------------------
