### ISSUE TITLE
Screen orientation issue

### ISSUE THREAD

**Issue by prooshani** [flutter-package/flutter_scan#13]
Hi,

I am trying to use this plug-in but have problem with screen orientation.

Whenever the controller starts, the screen orientation forces to portrait. I am developing an app with responsive orientation and this affect the job I am doing with the barcode scan.
In addition, after scanning the barcode and returning from the capture screen, the main screen persists on portrait mode which is not suitable for me.
Is there anyway to maintain original screen orientation when the controller starts the barcode scanView?

Thanks for your helps.

**Comment by chavesgu** [comment]
Currently plugin is not support landscape.

----------

该邮件从移动设备发送



--------------原始邮件--------------
发件人："Prooshani ***@***.***&gt;;
发送时间：2021年6月6日(星期天) 凌晨1:51
收件人："flutter-package/flutter_scan" ***@***.***&gt;;
抄送："Subscribed ***@***.***&gt;;
主题：[flutter-package/flutter_scan] Screen orientation issue (#13)
-----------------------------------

 

 
Hi,
 
I am trying to use this plug-in but have problem with screen orientation.
 
Whenever the controller starts, the screen orientation forces to portrait. I am developing an app with responsive orientation and this affect the job I am doing with the barcode scan.
 In addition, after scanning the barcode and returning from the capture screen, the main screen persists on portrait mode which is not suitable for me.
 Is there anyway to maintain original screen orientation when the controller starts the barcode scanView?
 
Thanks for your helps.

**Comment by prooshani** [comment]
Ok, thanks.

Already switched to another plug-in which supports orientations.

Good luck.

**Comment by nicolasbmorais** [comment]
@prooshani Which other did you use?

**Comment by prooshani** [comment]
> @prooshani Which other did you use?

barcode_scan2 and google_ml_kit
