### ISSUE TITLE
The code scanning line of Android 11 cannot move up and down.

### ISSUE THREAD

**Issue by qifendev** [flutter-package/flutter_scan#15]
The code scanning line of Android 11 cannot move up and down. It is always on the top and cannot be hidden. Recently, this library is needed. Please solve this problem as soon as possible. However, the IOS platform moves up and down normally.
![3DF97DA9522C814723C940013107BCD2](https://user-images.githubusercontent.com/45928182/124894694-76aac880-e00e-11eb-9d28-9ef25d6d43a0.jpg)

**Comment by chavesgu** [comment]
I test on Android 11, it work well.

**Comment by qifendev** [comment]
My phone model is Redmi K30i, and other phones on my side are also normal

**Comment by qifendev** [comment]
Another problem is that only square blocks are valid in the scan code area. I want to scan the QR code in the full screen.

**Comment by chavesgu** [comment]
> Another problem is that only square blocks are valid in the scan code area. I want to scan the QR code in the full screen.

You should read doc carefully!

**Comment by qifendev** [comment]
![image](https://user-images.githubusercontent.com/45928182/147070220-4f5d5795-ed72-4956-b753-98c80061741a.png)

This is a square

**Comment by qifendev** [comment]
![image](https://user-images.githubusercontent.com/45928182/147070424-9713fb05-4f3f-4559-9445-f1cb94513c1c.png)


I mean if you want this QR code, you can also scan it

**Comment by chavesgu** [comment]
> ![image](https://user-images.githubusercontent.com/45928182/147070424-9713fb05-4f3f-4559-9445-f1cb94513c1c.png)
> 
> I mean if you want this QR code, you can also scan it

No, if set scale 1, there is no square

**Comment by qifendev** [comment]
![image](https://user-images.githubusercontent.com/45928182/147071716-46bb4342-42f5-406e-b386-519ab3b23e2c.png)


It becomes like this after setting it to 1

**Comment by chavesgu** [comment]
yeah   correct behaviour

**Comment by chavesgu** [comment]
scan line animation is still not run?

**Comment by qifendev** [comment]
I think you can make this square frame better, and then there can be a square frame in the full screen state. Most softwares are like this.

**Comment by qifendev** [comment]
Running scanline animation is running

**Comment by chavesgu** [comment]
> I think you can make this square frame better, and then there can be a square frame in the full screen state. Most softwares are like this.

why draw square in full mode?

**Comment by qifendev** [comment]
I come from China, and almost all large-scale software in China is like this

**Comment by chavesgu** [comment]
你别搞了  你还china  哪个软件全屏扫码 还有框的。。

**Comment by qifendev** [comment]
qq 微博 多的是

**Comment by qifendev** [comment]
有很多的

**Comment by chavesgu** [comment]
就产品设计来说    全屏的扫码就不应该再去引导用户把码放到框里。。你非要这么玩   你可以自己画一个框。。或者fork一下  实现自己的逻辑

**Comment by qifendev** [comment]
无所谓了，公司的项目，我是建议你

**Comment by qifendev** [comment]
我都打开扫码页面了，我的目的一定是扫码，你为什么要让我放到框里扫码
