### ISSUE TITLE
ScanView只要和webview_flutter的WebView在同一个界面显示就无法看到扫码的过程（ScanView这块黑屏，实际不影响扫码结果，注：滚动界面时可以正常看到ScanView的渲染界面）

### ISSUE THREAD

**Issue by yangshangbo** [flutter-package/flutter_scan#24]
- [x] I have read the [Get Started - Installation](https://inappwebview.dev/docs/get-started/installation/) section
- [x] I have read and done the [Get Started - Setup Android](https://inappwebview.dev/docs/get-started/setup-android/) section
- [x] I have read and done the [Get Started - Setup iOS](https://inappwebview.dev/docs/get-started/setup-ios/) section
- [x] I have already searched for the same problem

## Environment

| Technology           | Version       |
| -------------------- | ------------- |
| Flutter version      |     2.5.2            |
| Plugin version       |    ^1.5.0           |
| Android version      |    11.x           |
| iOS version          |               |
| Xcode version        |               |

Device information: 

## Description

**Expected behavior:**

**Current behavior:**

## Steps to reproduce

1. This
2. Than that
3. Then

## Stacktrace/Logcat

**Comment by chavesgu** [comment]
我自己使用的是flutter_inappwebview这个webview插件    没有出现你说的问题  你试一下
![IMG_2954](https://user-images.githubusercontent.com/20633606/142090868-e4ed8e68-9f26-4f53-ba85-9e571d2dc20a.PNG)

**Comment by yangshangbo** [comment]
> 我自己使用的是flutter_inappwebview这个webview插件 没有出现你说的问题 你试一下 ![IMG_2954](https://user-images.githubusercontent.com/20633606/142090868-e4ed8e68-9f26-4f53-ba85-9e571d2dc20a.PNG)

嗯，试了一下这个插件确实没问题，感谢。你这个扫码的插件能不能切换摄像头？

**Comment by chavesgu** [comment]
官方的几个插件  都有一些奇怪的问题、    哪有用前置摄像头扫码的。。。。我没空搞这个二愣子功能
