### ISSUE TITLE
打包 flutter run --release  进入会闪退

### ISSUE THREAD

**Issue by ximenqing183** [flutter-package/flutter_scan#28]
打包 flutter run --release  进入会闪退

**Comment by ximenqing183** [comment]
E/AndroidRuntime(16547): FATAL EXCEPTION: main
E/AndroidRuntime(16547): Process: com.ly.asd.andiver_mobile, PID: 16547
E/AndroidRuntime(16547): java.lang.RuntimeException: java.lang.NoSuchMethodException: e.h.c.e.values []
E/AndroidRuntime(16547):        at java.lang.Enum.enumValues(Enum.java:270)
E/AndroidRuntime(16547):        at java.lang.Enum.access$000(Enum.java:61)
E/AndroidRuntime(16547):        at java.lang.Enum$1.create(Enum.java:277)
E/AndroidRuntime(16547):        at java.lang.Enum$1.create(Enum.java:275)
E/AndroidRuntime(16547):        at libcore.util.BasicLruCache.get(BasicLruCache.java:63)
E/AndroidRuntime(16547):        at java.lang.Enum.getSharedConstants(Enum.java:289)
E/AndroidRuntime(16547):        at java.lang.Class.getEnumConstantsShared(Class.java:2428)
E/AndroidRuntime(16547):        at java.util.EnumMap.getKeyUniverse(EnumMap.java:755)
E/AndroidRuntime(16547):        at java.util.EnumMap.<init>(EnumMap.java:138)
E/AndroidRuntime(16547):        at com.journeyapps.barcodescanner.p.a(Unknown Source:4)
E/AndroidRuntime(16547):        at com.journeyapps.barcodescanner.BarcodeView.D(:2)
E/AndroidRuntime(16547):        at com.journeyapps.barcodescanner.BarcodeView.H(Unknown Source:21)
E/AndroidRuntime(16547):        at com.journeyapps.barcodescanner.BarcodeView.u(Unknown Source:0)
E/AndroidRuntime(16547):        at com.journeyapps.barcodescanner.k.z(Unknown Source:28)
E/AndroidRuntime(16547):        at com.journeyapps.barcodescanner.k.A(Unknown Source:48)
E/AndroidRuntime(16547):        at com.journeyapps.barcodescanner.k.d(:5)
E/AndroidRuntime(16547):        at com.journeyapps.barcodescanner.k$b.handleMessage(Unknown Source:13)
E/AndroidRuntime(16547):        at android.os.Handler.dispatchMessage(Handler.java:106)
E/AndroidRuntime(16547):        at android.os.Looper.loop(Looper.java:219)
E/AndroidRuntime(16547):        at android.app.ActivityThread.main(ActivityThread.java:8668)
E/AndroidRuntime(16547):        at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(16547):        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
E/AndroidRuntime(16547):        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1109)
E/AndroidRuntime(16547): Caused by: java.lang.NoSuchMethodException: e.h.c.e.values []
E/AndroidRuntime(16547):        at java.lang.Class.getMethod(Class.java:2072)
E/AndroidRuntime(16547):        at java.lang.Class.getDeclaredMethod(Class.java:2050)
E/AndroidRuntime(16547):        at java.lang.Enum.enumValues(Enum.java:267)
E/AndroidRuntime(16547):        ... 22 more

**Comment by chavesgu** [comment]
I run example in release mode, works fine

**Comment by chavesgu** [comment]
> same issue here, it works well for debug mode, but for release apk it will crash the app

provide your android version and run example with --release --verbose
