### ISSUE TITLE
从扫码页面打开新的一个页面然后返回扫码页面，扫码页面会黑屏，只显示扫码框，背景是全黑的。

### ISSUE THREAD

**Issue by gdmec07150725** [flutter-package/flutter_scan#31]
- [x] I have read the [Get Started - Installation](https://inappwebview.dev/docs/get-started/installation/) section
- [x] I have read and done the [Get Started - Setup Android](https://inappwebview.dev/docs/get-started/setup-android/) section
- [x] I have read and done the [Get Started - Setup iOS](https://inappwebview.dev/docs/get-started/setup-ios/) section
- [x] I have already searched for the same problem

## Environment

| Technology           | Version       |
| -------------------- | ------------- |
| Flutter version      |      2.6.0-12.0.pre         |
| Plugin version       |    1.4.3           |
| Android version      |      11.x         |
| iOS version          |               |
| Xcode version        |               |

Device information: xiaomi Note9 pro  or  other android mobile

## Description

**Expected behavior:** 新页面返回到扫码页面，不黑屏

**Current behavior:**  新页面返回扫码页面，黑屏

## Steps to reproduce

![微信图片_20211213185250](https://user-images.githubusercontent.com/21993223/145799909-00559e36-8b99-425f-b38a-4f8ca1fa1ed7.jpg)

![微信图片_20211213185335](https://user-images.githubusercontent.com/21993223/145799973-b85fdff4-8f97-4a46-a15b-628694c2d62c.jpg)

![微信图片_20211213185341](https://user-images.githubusercontent.com/21993223/145799984-3d71eb42-c4ef-4534-8833-2946e3cf0935.jpg)

## Stacktrace/Logcat

**Comment by chavesgu** [comment]
I do not know how you did,but the best way is call `controller.pause()` when you entry new page and call `controller.resume()` when you back scan page

**Comment by chavesgu** [comment]
And do not use flutter hot reload in ScanView page,you should reopen ScanView page after hot reload

**Comment by gdmec07150725** [comment]
![image](https://user-images.githubusercontent.com/21993223/145917841-1102d980-49af-475c-b6b0-f7c6a809ee06.png)

I already use `controller.pause( )` and `controller.resume()` but this problem still exists

**Comment by chavesgu** [comment]
> ![image](https://user-images.githubusercontent.com/21993223/145917841-1102d980-49af-475c-b6b0-f7c6a809ee06.png)
> 
> I already use `controller.pause( )` and `controller.resume()` but this problem still exists

I can not reappear in example.And I face this problem with flutter hot reload.
You can test with github example

**Comment by gdmec07150725** [comment]
I  already reslove this problem, thanks. Beause of the new Pgae had the keyboard , i did not close the keyboard, when back scan page

**Comment by chavesgu** [comment]
好的
