### ISSUE TITLE
could not scan dark background + bright code on Android. Works fine on iOS.

### ISSUE THREAD

**Issue by terrytz** [flutter-package/flutter_scan#34]
could not scan dark background + light color code on Android. 
Parsing from image works fine on Android, but camera scan don't work for this scenario.
Camera scan and image parse both work fine on iOS for bright

Example QR code:
![qrcode](https://user-images.githubusercontent.com/3625602/147038278-6a1e23f5-0cb5-494f-be2c-c11a6a738138.png)
.

**Comment by chavesgu** [comment]
I will check this

**Comment by chavesgu** [comment]
I publish `v1.5.1`.
Please check.

**Comment by terrytz** [comment]
Works now! that was quick, thanks!
