### ISSUE TITLE
从其他页面打开二维码扫描页面会闪屏

### ISSUE THREAD

**Issue by HZRZCW** [flutter-package/flutter_scan#7]
我从一个页面打开封装好的二维码页面，每次打开页面都会闪一下~想知道这个是我没处理好页面转场还是这个插件的问题？

**Comment by chavesgu** [comment]
发个动图看看

**Comment by chavesgu** [comment]
flutter的视图和原生view不太契合的  如果你觉得动画体验不好   你可以尝试完全进入页面之后再渲染原生view

**Comment by HZRZCW** [comment]
好的，谢谢。

**Comment by chavesgu** [comment]
> 好的，谢谢。

你可以把Scaffold的 backgroundColor 设为 Colors.black
