### ISSUE TITLE
I want to change the position of the ScanView As it always show up at the center of the screen . 

### ISSUE THREAD

**Issue by gengbowen** [flutter-package/flutter_scan#8]
As the ScanView window always show up at the center of the screen . 
I want to change the position of the ScanView . such as put it at the top of the window ,
but It seems that no such attributes there that I can set to change it
 
![无标题](https://user-images.githubusercontent.com/43195260/111743514-c715e300-88c4-11eb-9b99-e73cd11ccc64.png)

hope get your kindly help
thks

**Comment by chavesgu** [comment]
I‘m so sorry. The scan area is set to center default. there is no attr to change it
If you want to change, you need fork this project.

I would be happy to provide more attributes to control it,but  No time recently

**Comment by gengbowen** [comment]
So glad to get your reply
I'll fork and read your code to see if i can do some contribute to this project


Regards&nbsp;


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "flutter-package/flutter_scan"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年3月19日(星期五) 晚上9:20
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [flutter-package/flutter_scan] I want to change the position of the ScanView As it always show up at the center of the screen .  (#8)





 
I‘m so sorry. The scan area is set to center default. there is no attr to change it
 If you want to change, you need fork this project.
 
I would be happy to provide more attributes to control it,but  No time recently
