### ISSUE TITLE
How can i get qrcode from image?

### ISSUE THREAD

**Issue by KrupaHingrajia** [flutter-package/flutter_scan#9]
String qrcode = await Scan.parse(res[0].path);
get qrcode string from image is giving me qrcode null.

**Comment by chavesgu** [comment]
please provider your qrcode pic for me test

**Comment by KrupaHingrajia** [comment]
![Screenshot 2021-04-22 at 10 04 11 AM](https://user-images.githubusercontent.com/80324504/115656065-1e8af100-a352-11eb-8195-10f902427d5d.png)

**Comment by KrupaHingrajia** [comment]
// import 'package:flutter/material.dart';
//
//
//
// class Scan extends StatefulWidget {
//   final GlobalKey<ScaffoldState> parentScaffoldKey;
//
//   const Scan({Key key, this.parentScaffoldKey}) : super(key: key);
//
//   @override
//   _ScanState createState() => _ScanState();
// }
//
// class _ScanState extends State<Scan> {
//   final GlobalKey<ScaffoldState> scanScaffoldKey = GlobalKey<ScaffoldState>();
//   String _platformVersion = 'Unknown';
//   //
//   // ScanController controller = ScanController();
//   // String qrcode = 'Unknown';
//   //
//   //
//   // @override
//   // void initState() {
//   //   super.initState();
//   //   initPlatformState();
//   // }
//   //
//   // Future<void> initPlatformState() async {
//   //   String platformVersion;
//   //   try {
//   //     platformVersion = await Scan.platformVersion;
//   //   } on PlatformException {
//   //     platformVersion = 'Failed to get platform version.';
//   //   }
//   //   if (!mounted) return;
//   //
//   //   setState(() {
//   //     _platformVersion = platformVersion;
//   //   });
//   // }
//
//
//   @override
//   Widget build(BuildContext context) {
//     return Scaffold(
//       key: scanScaffoldKey,
//       body: SafeArea(
//         child: Container(
//             child: Stack(
//           children: [
//
//           ],
//         )),
//       ),
//     );
//   }
// }
import 'package:flutter/material.dart';
import 'dart:async';
import 'package:flutter/services.dart';
import 'package:fstore/screens/found_item/found_item.dart';
import 'package:image_picker/image_picker.dart';
import 'package:scan/scan.dart';

class ScanWidget extends StatefulWidget {
  final GlobalKey<ScaffoldState> parentScaffoldKey;

  const ScanWidget({Key key, this.parentScaffoldKey}) : super(key: key);

  @override
  _ScanState createState() => _ScanState();
}

class _ScanState extends State<ScanWidget> {
  final GlobalKey<ScaffoldState> scanScaffoldKey = GlobalKey<ScaffoldState>();
  String _platformVersion = 'Unknown';

  bool issaved = false;

  ScanController controller = ScanController();
  String qrcode = 'Unknown';

  @override
  void initState() {
    super.initState();
    initPlatformState();
  }

  Future<void> initPlatformState() async {
    String platformVersion;
    try {
      platformVersion = await Scan.platformVersion;
    } on PlatformException {
      platformVersion = 'Failed to get platform version.';
    }
    if (!mounted) return;

    setState(() {
      _platformVersion = platformVersion;
    });
  }

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
          key: scanScaffoldKey,
          body: SafeArea(
            child: Container(
              child: Stack(
                children: [
                  ScanView(
                    controller: controller,
                    scanAreaScale: .7,
                    scanLineColor: Color(0xFF50C6FB),
                    onCapture: (data) {
                      setState(() {
                        qrcode = data;
                      });
                      if (qrcode != 'unknow') {
                        Navigator.of(context).push(
                            MaterialPageRoute(builder: (_) => FoundItem()));
                      } 
                    },
                  ),
                  Positioned(
                    top: 35,
                    right: 35,
                    child: Container(
                      decoration: new BoxDecoration(
                        color: Colors.white,
                        borderRadius: BorderRadius.circular(100),
                      ),
                      width: 145.0,
                      height: 70.0,
                      child: Padding(
                        padding: const EdgeInsets.only(left: 20.0, right: 20.0),
                        child: Row(
                          children: [
                            GestureDetector(
                                onTap: () async {
                                  var res = await ImagePicker().getImage(source: ImageSource.gallery);
                                  if (res != null) {
                                    print("${res.path}");
                                    qrcode = await Scan.parse(res.path);
                                    print("$qrcode");
                                  }
                                },
                                child: Image.asset(
                                    'assets/images/dappl/gallrey-image.png')),
                            Spacer(),
                            GestureDetector(
                                onTap: () {
                                  setState(() {
                                    if (issaved) {
                                      issaved = false;
                                    } else {
                                      issaved = true;
                                    }
                                  });
                                  controller.toggleTorchMode();
                                },
                                child: issaved == false
                                    ?  Image.asset(
                                    'assets/images/dappl/Icon ionic-ios-flash_gray.png')
                                    : Image.asset(
                                        'assets/images/dappl/flash_image.png')),
                          ],
                        ),
                      ),
                    ),
                  ),
                  Padding(
                    padding: const EdgeInsets.only(bottom: 65.0),
                    child: Align(
                      alignment: Alignment.bottomCenter,
                      child: Container(
                        height: 50,
                        width: 250,
                        decoration: new BoxDecoration(
                            color: Color(0xFF50C6FB),
                            borderRadius: BorderRadius.circular(10.0)),
                        child: Center(
                          child: GestureDetector(
                            onTap: () {
                              controller.resume();
                            },
                            child: Text(
                              "Cancel scaning",
                              style: TextStyle(
                                  color: Color(0xFFF8FDFF),
                                  fontFamily: 'TT Commons',
                                  fontWeight: FontWeight.w600,
                                  fontSize: 18.0),
                            ),
                          ),
                        ),
                      ),
                    ),
                  )
                ],
              ),
            ),
          )
          ),
    );
  }
}

**Comment by KrupaHingrajia** [comment]
import 'package:flutter/material.dart';
import 'dart:async';
import 'package:flutter/services.dart';
import 'package:fstore/screens/found_item/found_item.dart';
import 'package:image_picker/image_picker.dart';
import 'package:scan/scan.dart';

class ScanWidget extends StatefulWidget {
  final GlobalKey<ScaffoldState> parentScaffoldKey;

  const ScanWidget({Key key, this.parentScaffoldKey}) : super(key: key);

  @override
  _ScanState createState() => _ScanState();
}

class _ScanState extends State<ScanWidget> {
  final GlobalKey<ScaffoldState> scanScaffoldKey = GlobalKey<ScaffoldState>();
  String _platformVersion = 'Unknown';

  bool issaved = false;

  ScanController controller = ScanController();
  String qrcode = 'Unknown';

  @override
  void initState() {
    super.initState();
    initPlatformState();
  }

  Future<void> initPlatformState() async {
    String platformVersion;
    try {
      platformVersion = await Scan.platformVersion;
    } on PlatformException {
      platformVersion = 'Failed to get platform version.';
    }
    if (!mounted) return;

    setState(() {
      _platformVersion = platformVersion;
    });
  }

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
          key: scanScaffoldKey,
          body: SafeArea(
            child: Container(
              child: Stack(
                children: [
                  ScanView(
                    controller: controller,
                    scanAreaScale: .7,
                    scanLineColor: Color(0xFF50C6FB),
                    onCapture: (data) {
                      setState(() {
                        qrcode = data;
                      });
                      if (qrcode != 'unknow') {
                        Navigator.of(context).push(
                            MaterialPageRoute(builder: (_) => FoundItem()));
                      }
                    },
                  ),
                  Positioned(
                    top: 35,
                    right: 35,
                    child: Container(
                      decoration: new BoxDecoration(
                        color: Colors.white,
                        borderRadius: BorderRadius.circular(100),
                      ),
                      width: 145.0,
                      height: 70.0,
                      child: Padding(
                        padding: const EdgeInsets.only(left: 20.0, right: 20.0),
                        child: Row(
                          children: [
                            GestureDetector(
                                onTap: () async {
                                  var res = await ImagePicker().getImage(source: ImageSource.gallery);
                                  if (res != null) {
                                    print("${res.path}");
                                    qrcode = await Scan.parse(res.path);
                                    print("$qrcode");
                                  }
                                },
                                child: Image.asset(
                                    'assets/images/dappl/gallrey-image.png')),
                            Spacer(),
                            GestureDetector(
                                onTap: () {
                                  setState(() {
                                    if (issaved) {
                                      issaved = false;
                                    } else {
                                      issaved = true;
                                    }
                                  });
                                  controller.toggleTorchMode();
                                },
                                child: issaved == false
                                    ?  Image.asset(
                                    'assets/images/dappl/Icon ionic-ios-flash_gray.png')
                                    : Image.asset(
                                        'assets/images/dappl/flash_image.png')),
                          ],
                        ),
                      ),
                    ),
                  ),
                  Padding(
                    padding: const EdgeInsets.only(bottom: 65.0),
                    child: Align(
                      alignment: Alignment.bottomCenter,
                      child: Container(
                        height: 50,
                        width: 250,
                        decoration: new BoxDecoration(
                            color: Color(0xFF50C6FB),
                            borderRadius: BorderRadius.circular(10.0)),
                        child: Center(
                          child: GestureDetector(
                            onTap: () {
                              controller.resume();
                            },
                            child: Text(
                              "Cancel scaning",
                              style: TextStyle(
                                  color: Color(0xFFF8FDFF),
                                  fontFamily: 'TT Commons',
                                  fontWeight: FontWeight.w600,
                                  fontSize: 18.0),
                            ),
                          ),
                        ),
                      ),
                    ),
                  )
                ],
              ),
            ),
          )
          ),
    );
  }
}

**Comment by chavesgu** [comment]
you need provider me  which pic did you use, I test my pic work fine

**Comment by chavesgu** [comment]
did you get null on android

**Comment by KrupaHingrajia** [comment]
Yes , I get null on android.

**Comment by chavesgu** [comment]
I reappeared this bug, I will solve it

**Comment by KrupaHingrajia** [comment]
can you tell me how much time it will take?

**Comment by chavesgu** [comment]
I can't promise.....as soon as possible

**Comment by KrupaHingrajia** [comment]
ok

**Comment by chavesgu** [comment]
can you provide your qrcode image for me to test

**Comment by KrupaHingrajia** [comment]
![Screenshot 2021-04-22 at 1 09 51 PM](https://user-images.githubusercontent.com/80324504/115675332-2061ae00-a36c-11eb-9a01-05c1111b540a.png)

**Comment by chavesgu** [comment]
you can use version `1.2.0` to try again

**Comment by KrupaHingrajia** [comment]
did this code work for u while selecting image from galary in android device?

**Comment by chavesgu** [comment]
yes

**Comment by KrupaHingrajia** [comment]
Unfortunately, this code is not working for images in neither Android nor iOS. Any clue?

**Comment by chavesgu** [comment]
it work fine when I use image you provide

**Comment by KrupaHingrajia** [comment]
![Screenshot 2021-04-22 at 3 42 50 PM](https://user-images.githubusercontent.com/80324504/115697766-7c82fd00-a381-11eb-8d9f-351e8aeb4d6b.png)

**Comment by KrupaHingrajia** [comment]
see

**Comment by KrupaHingrajia** [comment]
qrcode null

**Comment by chavesgu** [comment]
you need provider
 your logcat

**Comment by chavesgu** [comment]
where are you from

**Comment by KrupaHingrajia** [comment]
surat

**Comment by chavesgu** [comment]
you must provide logcat and xcode log

**Comment by abdullah432** [comment]
I'm getting `Invalid argument(s)` exception

**Comment by SrivastavaShubham99** [comment]
Try this Scan.parse(imagePath).then((value) => print("$value"))
it worked for me
